// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiidyfidkhwtlyucacnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpaWR5Zmlka2h3dGx5dWNhY25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTkyOTAsImV4cCI6MjA2MTQzNTI5MH0.yY691_2ZeHP-gMJ8Osl4tLG7r05o5DyRmkXRRQp2yQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});